/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppProfileRouteImport } from './routes/_app.app.profile'
import { Route as AppAppExploreRouteImport } from './routes/_app.app.explore'
import { Route as AppAppDashboardRouteImport } from './routes/_app.app.dashboard'
import { Route as AppAppCommunityRouteImport } from './routes/_app.app.community'
import { Route as AppAppAdminRouteImport } from './routes/_app.app.admin'
import { Route as AppAppTripsIndexRouteImport } from './routes/_app.app.trips.index'
import { Route as AppAppTripsNewRouteImport } from './routes/_app.app.trips.new'
import { Route as AppAppTripsTripIdRouteImport } from './routes/_app.app.trips.$tripId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAppExploreRoute = AppAppExploreRouteImport.update({
  id: '/app/explore',
  path: '/app/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCommunityRoute = AppAppCommunityRouteImport.update({
  id: '/app/community',
  path: '/app/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAdminRoute = AppAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTripsIndexRoute = AppAppTripsIndexRouteImport.update({
  id: '/app/trips/',
  path: '/app/trips/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTripsNewRoute = AppAppTripsNewRouteImport.update({
  id: '/app/trips/new',
  path: '/app/trips/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTripsTripIdRoute = AppAppTripsTripIdRouteImport.update({
  id: '/app/trips/$tripId',
  path: '/app/trips/$tripId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAppAdminRoute
  '/app/community': typeof AppAppCommunityRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/explore': typeof AppAppExploreRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app/': typeof AppAppIndexRoute
  '/app/trips/$tripId': typeof AppAppTripsTripIdRoute
  '/app/trips/new': typeof AppAppTripsNewRoute
  '/app/trips/': typeof AppAppTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAppAdminRoute
  '/app/community': typeof AppAppCommunityRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/explore': typeof AppAppExploreRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app': typeof AppAppIndexRoute
  '/app/trips/$tripId': typeof AppAppTripsTripIdRoute
  '/app/trips/new': typeof AppAppTripsNewRoute
  '/app/trips': typeof AppAppTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/app/admin': typeof AppAppAdminRoute
  '/_app/app/community': typeof AppAppCommunityRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/_app/app/explore': typeof AppAppExploreRoute
  '/_app/app/profile': typeof AppAppProfileRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/trips/$tripId': typeof AppAppTripsTripIdRoute
  '/_app/app/trips/new': typeof AppAppTripsNewRoute
  '/_app/app/trips/': typeof AppAppTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/community'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/profile'
    | '/app/'
    | '/app/trips/$tripId'
    | '/app/trips/new'
    | '/app/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/community'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/profile'
    | '/app'
    | '/app/trips/$tripId'
    | '/app/trips/new'
    | '/app/trips'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/app/admin'
    | '/_app/app/community'
    | '/_app/app/dashboard'
    | '/_app/app/explore'
    | '/_app/app/profile'
    | '/_app/app/'
    | '/_app/app/trips/$tripId'
    | '/_app/app/trips/new'
    | '/_app/app/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/profile': {
      id: '/_app/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/explore': {
      id: '/_app/app/explore'
      path: '/app/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppAppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/community': {
      id: '/_app/app/community'
      path: '/app/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppAppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/admin': {
      id: '/_app/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/trips/': {
      id: '/_app/app/trips/'
      path: '/app/trips'
      fullPath: '/app/trips/'
      preLoaderRoute: typeof AppAppTripsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/trips/new': {
      id: '/_app/app/trips/new'
      path: '/app/trips/new'
      fullPath: '/app/trips/new'
      preLoaderRoute: typeof AppAppTripsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/trips/$tripId': {
      id: '/_app/app/trips/$tripId'
      path: '/app/trips/$tripId'
      fullPath: '/app/trips/$tripId'
      preLoaderRoute: typeof AppAppTripsTripIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppAdminRoute: typeof AppAppAdminRoute
  AppAppCommunityRoute: typeof AppAppCommunityRoute
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppExploreRoute: typeof AppAppExploreRoute
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppTripsTripIdRoute: typeof AppAppTripsTripIdRoute
  AppAppTripsNewRoute: typeof AppAppTripsNewRoute
  AppAppTripsIndexRoute: typeof AppAppTripsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAdminRoute: AppAppAdminRoute,
  AppAppCommunityRoute: AppAppCommunityRoute,
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppExploreRoute: AppAppExploreRoute,
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppTripsTripIdRoute: AppAppTripsTripIdRoute,
  AppAppTripsNewRoute: AppAppTripsNewRoute,
  AppAppTripsIndexRoute: AppAppTripsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
